#!/bin/bash

# Compile all Java files in the current directory
echo "Compiling all Java files..."
javac *.java

if [ $? -ne 0 ]; then
  echo "Compilation failed. Exiting."
  exit 1
fi

if [ $# -eq 1 ]; then
  # If a class name is provided as an argument, run only that class
  classname="$1"
  echo "Running $classname..."
  java "$classname"
  echo "----------------------------"
else
  # If no argument, run all classes
  for file in *.java; do
    classname="${file%.java}"
    echo "Running $classname..."
    java "$classname"
    echo "----------------------------"
  done
fi

# Cleanup: delete all .class files generated by javac
echo "Cleaning up generated .class files..."
rm -f *.class

echo "Cleanup complete."
