--Molten
-- map("n", "<leader>re", ":MoltenEvaluateOperator<cr>", { desc = "evaluate operator", silent = true })
-- map("n", "<leader>ro", ":noautocmd MoltenEnterOutput<cr>", { desc = "open output window", silent = true })
-- map("n", "<leader>rr", ":MoltenReevaluateCell<cr>", { desc = "re-eval cell", silent = true })
-- map("v", "<leader>r", ":<C-u>MoltenEvaluateVisual<cr>gv", { desc = "execute visual selection", silent = true })
-- map("n", "<leader>rh", ":MoltenEvaluateLine<cr>", { desc = "evaluate line", silent = true })
-- map("n", "<leader>rh", ":MoltenHideOutput<cr>", { desc = "close output window", silent = true })
-- map("n", "<leader>dd", ":MoltenDelete<cr>", { desc = "delete Molten cell", silent = true })
-- map("n", "<leader>rx", ":MoltenOpenInBrowser<cr>", { desc = "open output in browser", silent = true })
-- map("n", "<leader>rd", ":MoltenDeinit<cr>", { desc = "deinit ", silent = true })

-- map("n", "<leader>t", f.toggle_smart_terminal, { desc = "Toggle Smart Terminal Overlay" })
-- map("n", "<leader>tt", f.open_tab_terminal, { desc = "New Tab Terminal Interface" })
-- map("n", "<leader>DD", f.compile_and_run_cpp, { desc = "Compile, Debug, and Run C++ active script" })

-- functions

-- BigOpen function can be deleted(not used)

-- vim.api.nvim_create_user_command("BigOpen", function(opts)
--   local filepath = opts.args
--   if filepath == "" then
--     vim.notify("Please provide a file path.", vim.log.levels.ERROR)
--     return
--   end
--
--   -- 1. Safely blind Neovim before loading the buffer
--   vim.g.neovim_loading_bigfile = true
--   vim.opt.eventignore:append({ "BufReadPre", "BufReadPost", "FileType" })
--
--   -- 2. Use a protected execution block to guarantee cleanup happens no matter what
--   local success, err = pcall(function()
--     vim.cmd("edit " .. vim.fn.fnameescape(filepath))
--     local buf = vim.api.nvim_get_current_buf()
--
--     -- Strip performance killers locally
--     vim.opt_local.swapfile = false
--     vim.opt_local.undofile = false
--     vim.opt_local.foldmethod = "manual"
--     vim.opt_local.wrap = false
--     vim.opt_local.statuscolumn = ""
--     vim.opt_local.relativenumber = false
--     vim.opt_local.syntax = "off"
--
--     -- Disable Treesitter natively if active
--     pcall(vim.treesitter.stop, buf)
--
--     local clients = vim.lsp.get_clients({ bufnr = buf })
--     for _, client in ipairs(clients) do
--       vim.lsp.buf_detach_client(buf, client.id)
--     end
--   end)
--
--   -- 3. GUARANTEED TEARDOWN: This will run even if the edit block above fails
--   vim.opt.eventignore:remove({ "BufReadPre", "BufReadPost", "FileType" })
--   vim.g.neovim_loading_bigfile = false
--
--   -- If something did go wrong inside the edit block, let you know without breaking Neovim
--   if not success then
--     vim.notify("BigOpen encountered an error: " .. tostring(err), vim.log.levels.ERROR)
--   else
--     vim.notify("File opened in Fast Raw Mode.", vim.log.levels.WARN)
--   end
-- end, {
--   nargs = 1,
--   complete = "file",
--   desc = "Open a massive file instantly in raw text mode",
-- })

-- local function clean_and_append_spaces()
--   local buf = vim.api.nvim_get_current_buf()
--   if not vim.api.nvim_buf_is_valid(buf) then
--     return
--   end
--
--   -- Grab all raw text lines inside the currently active buffer
--   local lines = vim.api.nvim_buf_get_lines(buf, 0, -1, false)
--   local cleaned_lines = {}
--
--   local i = 1
--   while i <= #lines do
--     local current_line = lines[i]
--     local next_line = lines[i + 1]
--
--     -- Match exact sequence: 'status:' followed by '  - baby'
--     if current_line:match("^status:%s*$") and next_line and next_line:match("^%s*-%s*baby%s*$") then
--       i = i + 2 -- Skip both block lines completely
--     else
--       -- If the line contains at least one non-whitespace character/symbol
--       if current_line:match("%S") then
--         -- Trim any existing trailing spaces first to avoid making a giant pile of spaces,
--         -- then cleanly append exactly two spaces to the end of the line.
--         current_line = current_line:gsub("%s*$", "") .. "  "
--       end
--       table.insert(cleaned_lines, current_line)
--       i = i + 1
--     end
--   end
--
--   -- Write the transformed text layout safely back down over the active Neovim buffer
--   vim.api.nvim_buf_set_lines(buf, 0, -1, false, cleaned_lines)
-- end
-- Create a user command so you can execute it manually with :CleanMarkdown
-- vim.api.nvim_create_user_command("CleanMarkdown", clean_and_append_spaces, {})
--
-- -- Optional: Map it to a convenient hotkey shortcut layer (e.g., <leader>mc)
-- vim.keymap.set("n", "<leader>mc", clean_and_append_spaces, { desc = "Clean Status Meta & Add Trailing Spaces" })
